Implements operations 0 through 8 of the revised spec.
WICG/ab-worker-prototype pull request #7
Opened 2022-10-26 21:26 UTC by alexnj

Operations are now defined and portable across PRE_UA and ON_UA. See the updated EXPLAINER.md for supported operations.

Other changes:
 * Point to a new gist that has the revised spec.
 * Switch to Closure Compiler.

/cc @micahheineckoptimizely @smoroz

2022-10-27 14:59 UTC, micahheineckoptimizely requested changes
Mostly LGTM, only potential minor changes.

2022-10-27 14:59 UTC, micahheineckoptimizely commented on src/constants.js
> +  OP_PREPEND: 2,
Was code `1` intentionally skipped?

2022-10-27 14:59 UTC, micahheineckoptimizely commented on src/pre-ua-transform-applicator.js
> +  [OPERATIONS.OP_INSERT_BEFORE]: ['before', (html) => [html, {html: true}]],
This is very clever 😄 
I learned a few things today, thanks!

2022-10-27 14:59 UTC, micahheineckoptimizely commented on src/config.js
> +    return `https://gist.githubusercontent.com/alexnj/56e6a1bed280d3111e623f7f6da4d139/raw/${example}`;
I left a comment on the new version: https://gist.github.com/alexnj/56e6a1bed280d3111e623f7f6da4d139?permalink_comment_id=4349894#gistcomment-4349894

2022-11-09 14:23 UTC, alexnj commented on src/constants.js
> +  OP_PREPEND: 2,
We had `OP_CUSTOM_CSS` that we retired.

2022-11-09 14:23 UTC, merged